# Generated by Django 5.1.3 on 2025-02-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_create_initial_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='status',
        ),
    ]
