# Generated by Django 5.1.3 on 2024-12-17 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=255, verbose_name='ที่อยู่')),
                ('city', models.CharField(max_length=100, verbose_name='เมือง')),
                ('state', models.CharField(max_length=100, verbose_name='จังหวัด')),
                ('zip_code', models.CharField(max_length=10, verbose_name='รหัสไปรษณีย์')),
                ('country', models.CharField(default='ประเทศไทย', max_length=100, verbose_name='ประเทศ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
