# Generated by Django 5.1.3 on 2024-12-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='ไม่ระบุ', max_length=255, verbose_name='ชื่อ-นามสกุล'),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='000-000-0000', max_length=15, verbose_name='เบอร์ติดต่อ'),
        ),
    ]
