# Generated by Django 5.1.3 on 2024-12-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_address_name_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อ-นามสกุล'),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='เบอร์ติดต่อ'),
        ),
    ]
