# Generated by Django 5.1.3 on 2025-02-15 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='order',
            name='buyer_message',
            field=models.TextField(blank=True, null=True, verbose_name='ข้อความถึงผู้ขาย'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=4, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('general', 'ทั่วไป'), ('clothing', 'เสื้อผ้า'), ('electronics', 'อุปกรณ์อิเล็กทรอนิกส์'), ('books', 'หนังสือ')], default='general', max_length=50),
        ),
    ]
